[project]
name = "jojcc"
version = "0.1.0"
description = "Joaquim's Own Jank C Compiler"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "shared",
    # ipython is not _strickly_ necessary
    # But trust on this one - you shan't be able to live without `pdb`
    "ipython",
    "pydantic>=2.12.5",
    "ruff>=0.14.14",
]

[project.optional-dependencies]
# LSP used.
# Basedpyright is `based` unlike the _cringe_ pyright
# I install basedpyright globally using npm, but it's available as a standard pypi package.
lsp = [
    "basedpyright>=1.37.2",
]

[tool.uv.workspace]
members = [
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "shared",
]

[tool.uv.sources]
chapter1 = { workspace = true }
chapter2 = { workspace = true }
chapter3 = { workspace = true }
chapter4 = { workspace = true }
shared = { workspace = true }

[tool.ruff]
extend-exclude = [
    # External code yo
    "writing-a-c-compiler-tests",
]

[tool.pyright]
exclude = [
    '**/.venv',
    'writing-a-c-compiler-tests/'
]
