[project]
name = "jojcc"
version = "0.1.0"
description = "Joaquim's Own Jank C Compiler"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "shared",
    # ipython is not _strickly_ necessary
    # But trust on this one - you shan't be able to live without `pdb`
    "ipython",
    "pydantic>=2.12.5",
    "ruff>=0.14.14",
    "chapter5",
    "pytest>=9.0.2",
    "chapter6",
    "chapter7",
    "chapter8",
    "chapter9",
    "chapter10",
    "chapter11",
    "chapter12",
    "chapter13",
]

[project.optional-dependencies]
# LSP used.
# Basedpyright is `based` unlike the _cringe_ pyright
# I install basedpyright globally using npm, but it's available as a standard pypi package.
lsp = [
    "basedpyright>=1.37.2",
]

[tool.uv.workspace]
members = [
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "shared",
    "chapter5",
    "chapter6",
    "chapter7",
    "chapter8",
    "chapter9",
    "chapter10",
    "chapter11",
    "chapter12",
    "chapter13",
]

[tool.uv.sources]
chapter1 = { workspace = true }
chapter2 = { workspace = true }
chapter3 = { workspace = true }
chapter4 = { workspace = true }
shared = { workspace = true }
chapter5 = { workspace = true }
chapter6 = { workspace = true }
chapter7 = { workspace = true }
chapter8 = { workspace = true }
chapter9 = { workspace = true }
chapter10 = { workspace = true }
chapter11 = { workspace = true }
chapter12 = { workspace = true }
chapter13 = { workspace = true }

[tool.ruff]
extend-exclude = [
    # External code yo
    "writing-a-c-compiler-tests",
]
[tool.ruff.lint]
select = [
    # Subset of pycodestyle
    "E4",
    "E7",
    "E9",
    # pyflakes
    "F",
    # Bug-bear
    'B',
    # Deletes commented code
    'ERA',
    'S',
    'FBT',
    # Shadowing
    'A',
    # Comprehension stuff
    'C4',
    # debugger
    'DTZ',
    # Shebang checker
    'EXE',
    # Implicit string-concat
    'ISC',
    # Import conventions
    'ICN',
    # Goddamn __init__.py
    'INP',
    # Misc stuff
    # Mostly unecessary `pass`
    'PIE',
    # Look for `print`
    # We ignore it since I use it a lot on the compiler-driver
    # 'T20',
    # Pytest stuff
    'PT',
    # Return rules
    'RET',
    # "Simplifications"
    'SIM',
    # TODO stuff
    'TD',
    # Unused arguments
    'ARG',
    # Numpy-stuff
    'NPY',
    # Pandas stuff
    'PD',
    'PERF',
    'PLE',
    # python versioning stuff
    'UP',
    # Trivial refactoring things that sometimes slip through
    'FURB',
    # Ruff specific rules
    'RUF',
    # Prevent exception-handling antipatterns
    'TRY'
]

ignore = [
    # It's fine so long as the variable is a throw-away or meant to be a global
    'B039',
    # Asserts are fine
    'S101',
    # We validate everything anyway, so it's fine
    'S603',
    # There's no passwords here
    'S105',
    # It's too commmon to do `type =`
    'A001',
    'A002',
    # It's fine to have complex asserts
    'PT018',
    # These two are silly
    'RET501',
    'RET502',
    # Unecessary assignment before return is fine
    # It's obvious, and probably just there for flow
    'RET504',
    # If-else-expressions are sometimes too long
    'SIM108',
    # Not all todos need a stupid github link
    'TD003',
    # In this project - I'm the only dev, so no need to check
    'TD002',
    # Long messages are totally fine
    'TRY003',
]

[tool.ruff.format]
docstring-code-format = true

[tool.pyright]
exclude = [
    '**/.venv',
    'writing-a-c-compiler-tests/'
]
